
CREATE TYPE "event_status_enum" AS ENUM (
  'UPCOMING',
  'LIVE',
  'FINISHED',
  'CANCELLED'
);

CREATE TYPE "bet_status_enum" AS ENUM (
  'PENDING',
  'WON',
  'LOST',
  'VOID'
);


CREATE TABLE "bets" (
                        "bet_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        "user_id" BIGINT NOT NULL,
                        "stake" DECIMAL(15,2) NOT NULL,
                        "total_odd" DECIMAL(10,4) NOT NULL,
                        "potential_payout" DECIMAL(15,2) NOT NULL,
                        "bet_status" bet_status_enum NOT NULL DEFAULT 'PENDING',
                        "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "sports" (
                          "sport_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          "sport_name" VARCHAR(100) UNIQUE NOT NULL
);

CREATE TABLE "events" (
                          "event_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          "sport_id" INT NOT NULL,
                          "event_name" VARCHAR(255) NOT NULL,
                          "start_time" TIMESTAMP NOT NULL,
                          "event_status" event_status_enum NOT NULL
);

CREATE TABLE "markets" (
                           "market_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           "event_id" BIGINT NOT NULL,
                           "market_name" VARCHAR(100) NOT NULL,
                           "is_settled" BOOLEAN NOT NULL DEFAULT false
);

CREATE TABLE "odds" (
                        "odd_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        "market_id" BIGINT NOT NULL,
                        "outcome_name" VARCHAR(100) NOT NULL,
                        "odd_value" DECIMAL(10,4) NOT NULL,
                        "is_active" BOOLEAN NOT NULL DEFAULT true
);

CREATE TABLE "results" (
                           "result_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           "market_id" BIGINT UNIQUE NOT NULL,
                           "winning_odd_id" BIGINT NOT NULL,
                           "settled_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "bet_selections" (
                                  "selection_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                  "bet_id" BIGINT NOT NULL,
                                  "market_id" BIGINT NOT NULL,
                                  "odd_id" BIGINT NOT NULL,
                                  "odd_value_at_bet_time" DECIMAL(10,4) NOT NULL,
                                  "selection_status" bet_status_enum NOT NULL DEFAULT 'PENDING'
);

CREATE INDEX idx_bets_user_id ON bets(user_id);
CREATE INDEX idx_bets_created_at ON bets(created_at);
CREATE INDEX idx_events_sport_id ON events(sport_id);
CREATE INDEX idx_events_start_time ON events(start_time);
CREATE INDEX idx_markets_event_id ON markets(event_id);
CREATE INDEX idx_markets_is_settled ON markets(is_settled);
CREATE INDEX idx_odds_market_id ON odds(market_id);
CREATE INDEX idx_odds_is_active ON odds(is_active);
CREATE INDEX idx_odds_market_active ON odds(market_id, is_active);
CREATE INDEX idx_results_market_id ON results(market_id);
CREATE INDEX idx_bet_selections_bet_id ON bet_selections(bet_id);
CREATE INDEX idx_bet_selections_market_id ON bet_selections(market_id);
CREATE INDEX idx_bet_selections_odd_id ON bet_selections(odd_id);
CREATE INDEX idx_bet_selections_bet_market ON bet_selections(bet_id, market_id);

ALTER TABLE "events" ADD FOREIGN KEY ("sport_id") REFERENCES "sports" ("sport_id");
ALTER TABLE "markets" ADD FOREIGN KEY ("event_id") REFERENCES "events" ("event_id");
ALTER TABLE "odds" ADD FOREIGN KEY ("market_id") REFERENCES "markets" ("market_id");
ALTER TABLE "results" ADD FOREIGN KEY ("market_id") REFERENCES "markets" ("market_id");
ALTER TABLE "results" ADD FOREIGN KEY ("winning_odd_id") REFERENCES "odds" ("odd_id");
ALTER TABLE "bet_selections" ADD FOREIGN KEY ("bet_id") REFERENCES "bets" ("bet_id");
ALTER TABLE "bet_selections" ADD FOREIGN KEY ("market_id") REFERENCES "markets" ("market_id");
ALTER TABLE "bet_selections" ADD FOREIGN KEY ("odd_id") REFERENCES "odds" ("odd_id");