
CREATE TYPE "transaction_type_enum" AS ENUM (
  'DEPOSIT',
  'WITHDRAWAL',
  'BET_PLACEMENT',
  'BET_WINNING',
  'BET_REFUND'
);


CREATE TABLE "users" (
                         "user_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         "username" VARCHAR(50) UNIQUE NOT NULL,
                         "first_name" VARCHAR(50) NOT NULL,
                         "last_name" VARCHAR(50) NOT NULL,
                         "personal_id_number" VARCHAR(50) UNIQUE NOT NULL,
                         "password_hash" VARCHAR(255) NOT NULL,
                         "email" VARCHAR(100) UNIQUE NOT NULL,
                         "cash_balance" DECIMAL(15,2) NOT NULL DEFAULT 0,
                         "bonus_balance" DECIMAL(15,2) NOT NULL DEFAULT 0,
                         "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE "user_roles" (
                              "user_id" BIGINT NOT NULL,
                              "role_name" VARCHAR(50) NOT NULL,
                              PRIMARY KEY ("user_id", "role_name")
);

CREATE TABLE "transactions" (
                                "transaction_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                "user_id" BIGINT NOT NULL,
                                "transaction_type" transaction_type_enum NOT NULL,
                                "amount" DECIMAL(15,2) NOT NULL,
                                "related_bet_id" BIGINT,
                                "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "company_finances" (
                                    "id" INT PRIMARY KEY DEFAULT 1,
                                    "total_balance" DECIMAL(20,2) NOT NULL,
                                    "last_calculated_at" TIMESTAMP NOT NULL
);

CREATE INDEX idx_users_email ON users(email);
CREATE INDEX idx_users_personal_id_number ON users(personal_id_number);
CREATE INDEX idx_user_roles_user_id ON user_roles(user_id);
CREATE INDEX idx_transactions_user_id ON transactions(user_id);
CREATE INDEX idx_transactions_created_at ON transactions(created_at);
CREATE INDEX idx_transactions_related_bet_id ON transactions(related_bet_id);


ALTER TABLE "user_roles" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("user_id");
ALTER TABLE "transactions" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("user_id");